### ISSUE TITLE
Focuspoint Auswahl im Medienpool

### ISSUE THREAD

**Issue by olien** [olien/rex_focuspoint#12]
Cool wäre es doch wenn das schon angezeigt Bild benutzt wird. Die Größe finde ich vollkommen ausreichend um einen Punkt zu setzen und im Medienpool sparen wir Platz...

![focuspoint](https://cloud.githubusercontent.com/assets/330516/5280738/9476f9f4-7af5-11e4-9146-b23d76f53fa4.jpg)

**Comment by olien** [comment]
Hab ich eingebaut. Kann das mal jemand bitte testen :-)

**Comment by DanielWeitenauer** [comment]
Hi Oliver,

hab's gerade getestet. Leider startet focuspoint nicht. Wenn man es im jQuery-Kompatibilitätsmodus aufruft (jQuery statt $) geht es. Hab ich hier angepasst: #14.

**Comment by olien** [comment]
Hi Daniel, 

danke. Hab die Änderungen so übernommen.
Ich warte noch mal ob noch jemand testet. 

LG
Oliver

**Comment by olien** [comment]
Hat zufällig noch jemand getestet?

**Comment by olien** [comment]
Na dann...

**Comment by dpf-dd** [comment]
OK, eben getestet!

Sobald ich das AddOn Focuspoint installiere, zeigt mein Medienpool die Vorschau in Originalgröße!?
Wie krieg ich das wieder klein (also quasi das die Vorschau wieder durch den Image Manager gejagt wird "rex_media_details"?

Das setzen des Focuspoints funktioniert tadellos. Ist halt nur blöd, wenn ich von einer 1200px Grafik auf der X-Achse nur 300 Pixel sehe, den Focuspoint aber auf zB 600px setzen will...

Ansonsten sehr geiles Addon!
MfG dpf_dd

**Comment by dpf-dd** [comment]
Update:
Im Chrome tritt das Problem nicht auf - und der Firefox war noch v37...

**Comment by olien** [comment]
Hallo. Ich gucke es mir bei Gelegenheit an. Danke!
