### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by olien** [olien/rex_focuspoint#16]
@mhut47 Du schreibst auf deinem Profil "You should know me". 
Magst Du nicht in den REDAXO Slack Channel kommen?  

http://redaxo.org/slack/

**Comment by ghost** [comment]
nein

2017-11-07 9:30 GMT+01:00 Oliver Kreischer <notifications@github.com>:

**Comment by ghost** [comment]
@olien warum?

**Comment by olien** [comment]
Weil es dort viele nette Menschen gibt, es einfach Spaß macht und man sich austauschen kann.
(Ich wusste nicht wie ich anderes Kontakt zu dir aufnehmen konnte...)
