### ISSUE TITLE
Minimal Erklärung im AddOn selbst wäre super.

### ISSUE THREAD

**Issue by dergel** [olien/rex_focuspoint#2]
Sprich. Man hat links in der Navi "FocusPoint" zum anklicken und bekommt eine minimal Erklärung. z.B. wie ich das im Frontend integriere. Man könnte die "beispiel_modulausgabe.php" z.B. dort darstellen.

lg
Jan

**Comment by olien** [comment]
Hast du ja gemacht. Danke!
