### ISSUE TITLE
effect klasse noch anpassen

### ISSUE THREAD

**Issue by dergel** [olien/rex_focuspoint#6]
sobald mal einen focuspoint gesetzt hat - und dieser im image_manager mit der focuspoint klasse verwendet wird - ändert sich das bildformat, weil, abhaengig vom focuspoint, das größtmögliche format genommen wird.

das könnte man noch optional einsetzen. Bildformat beibehalten als checkbox wäre gut.

Eventuell könnte man auch einen Zoom noch mit einplanen.. Sowas wie .. Bildzoom zum focuspoint - in Prozent .. 25/50/75% reinzoomen.

**Comment by olien** [comment]
Addon wird (hier) nicht mehr weiter entwickelt…

https://github.com/FriendsOfREDAXO/focuspoint
